### ISSUE TITLE
Twitterログインでエラー

### ISSUE THREAD

**Issue by fukuiretu** [sekainohajimari/ikyusan-api#63]
```
Rendering 500 with exception: undefined method `token' for nil:NilClass
/Users/fukuiretu/development/workspace/github.com/sekainohajimari/ikyusan-api/app/serializers/user_serializer.rb:24:in `token'
/Users/fukuiretu/development/workspace/github.com/sekainohajimari/ikyusan-api/vendor/bundle/ruby/2.2.0/gems/active_model_serializers-0.9.3/lib/active_model/serializer.rb:160:in `block in attributes'
```

**Comment by fukuiretu** [comment]
UAでios or android判定してるからブラウザから普通に叩くとダメや。。。

**Comment by fukuiretu** [comment]
一旦iOS固定にして回避した。
